# Generated by Django 5.0.6 on 2024-08-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
