# Generated by Django 5.0.6 on 2025-03-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='date',
        ),
    ]
