# Generated by Django 5.0.6 on 2025-03-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_order_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
