# Generated by Django 5.0.6 on 2025-03-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orders_status_orders_total_alter_orders_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total',
            new_name='subtotal',
        ),
    ]
