# Generated by Django 5.0.6 on 2025-03-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_total_orders_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='subtotal',
            new_name='total',
        ),
    ]
